--- #YAML:1.0
name:               Squatting-On-Mojo
version:            0.03
abstract:           squat on top of Mojo
author:
    - John BEPPU <beppu@cpan.org>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mojo:       0.9002
    Squatting:  0.6
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
no_index:
    directory:
        - eg
        - t
